#!/bin/bash
# Creates baseline migration branch using file-copy approach

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

DESTINATION_DIR="${1:-$SCRIPT_DIR/destination}"

# Resolve directory path
if [[ "$DESTINATION_DIR" != /* ]]; then
    DESTINATION_DIR="$SCRIPT_DIR/$DESTINATION_DIR"
fi

# Validate destination directory exists
if [ ! -d "$DESTINATION_DIR" ]; then
    echo -e "${RED}Error: Destination directory not found: $DESTINATION_DIR${NC}"
    exit 1
fi

# Validate we have modified-files-list.txt
if [ ! -f "$SCRIPT_DIR/modified-files-list.txt" ]; then
    echo -e "${RED}Error: modified-files-list.txt not found${NC}"
    echo "Run ./run-all.sh first to generate file lists"
    exit 1
fi

echo "======================================"
echo "Baseline Migration: File Copy Approach"
echo "======================================"
echo ""
echo "Destination: $DESTINATION_DIR"
echo ""

# Step 1: Create baseline branch
cd "$DESTINATION_DIR"
echo "Creating baseline branch..."

# Check if we're already on the branch
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" == "migrate/file-baseline" ]; then
    echo -e "${YELLOW}Already on branch: migrate/file-baseline${NC}"
else
    # Check if branch already exists
    if git show-ref --verify --quiet refs/heads/migrate/file-baseline; then
        echo -e "${YELLOW}Branch migrate/file-baseline already exists${NC}"
        echo "Checking out existing branch..."
        git checkout migrate/file-baseline
    else
        echo "Creating new branch: migrate/file-baseline"
        git checkout -b migrate/file-baseline
    fi
fi
echo ""

# Step 2: Run existing migration (from repo root)
cd "$SCRIPT_DIR"
echo "Running file-based migration..."
./migrate-all.sh --yes source destination
echo ""

# Step 3: Check if there are changes to commit
cd "$DESTINATION_DIR"
if git diff --quiet && git diff --cached --quiet; then
    echo -e "${YELLOW}No changes to commit (files are already up to date)${NC}"
else
    echo "Committing changes..."
    git add .
    git commit -m "Migration baseline: File copy approach

This commit represents the desired end-state using file-based
copying from source repository. All files from modified-files-list.txt
have been copied over.

Generated by: baseline-migration.sh"
    echo -e "${GREEN}✓ Committed changes${NC}"
fi
echo ""

# Step 4: Tag for later comparison
echo "Tagging commit..."
# Delete tag if it already exists
if git tag -l | grep -q "^migrate-file-baseline$"; then
    git tag -d migrate-file-baseline
    echo "Removed existing tag"
fi
git tag migrate-file-baseline
echo -e "${GREEN}✓ Tagged commit: migrate-file-baseline${NC}"
echo ""

echo "======================================"
echo "✓ Baseline migration complete!"
echo "======================================"
echo ""
echo "Created:"
echo "  - Branch: migrate/file-baseline"
echo "  - Tag: migrate-file-baseline"
echo ""
echo "This baseline represents the desired end-state for comparison."
